### ISSUE TITLE
onNotification event is not fired on ios if app is not running

### ISSUE THREAD

**Issue by JumBay** [ostownsville/cordova-plugin-fcm#18]
Hi,

On iOS (11), if I receive a notification but the app is killed, tapping on the notification opens the app but the onNotification method is never called.

Works fine on Android.

Any idea how to fix it?

Thanks.

**Comment by ironbone** [comment]
Confirmed. See my report for mor tests.

**Comment by luigi37** [comment]
Confirmed.
Tried with iPhone 5C 10.3.3 and iPhone 5S 11.0.3 with same behaviour:
1- app in foreground: the notification call onNotification event
2- app in background: clicking the notification you open the app and call onNotification event
3- app killed: clicking the notification you open the app BUT NOT call to onNotification event
4- phone just restarted: clicking the notification you open the app BUT NOT call to onNotification event

**Comment by ironbone** [comment]
The same im my tests:
https://github.com/ostownsville/cordova-plugin-fcm/issues/19#issuecomment-337570716

**Comment by chrisjpalmer** [comment]
Hi guys. If you don't mind I might close this issue and like @ironbone said checkout https://github.com/ostownsville/cordova-plugin-fcm/issues/19 instead.
