### ISSUE TITLE
NPM Registry Issue?

### ISSUE THREAD

**Issue by junerockwell** [ostownsville/cordova-plugin-fcm#20]
Cannot install this forked version of the Cordova-plugin-fcm. Below is the command I used and the error message.

````
ITMBA8-2:Appname me$ sudo cordova plugin add https://github.com/ostownsville/cordova-plugin-fcm.git
Error: Failed to fetch plugin https://github.com/ostownsville/cordova-plugin-fcm.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/ostownsville/cordova-plugin-fcm.git /Users/me/.npm/_cacache/tmp/git-clone-64d1cb55
npm ERR! /Users/me/.npm/_cacache/tmp/git-clone-64d1cb55/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2017-10-18T22_34_16_880Z-debug.log
````

Using:
MacOSX 10.12.16
Node: v8.0.0
Npm: v5.0.0
Cordova: 7.0.1
Ionic CLI: 3.7.0
Ionic Framework: 1.3.3

**Comment by chrisjpalmer** [comment]
Hi there.

This is strange. Running this command (as specified by the documentation) does work for me:
`cordova plugin add https://github.com/ostownsville/cordova-plugin-fcm.git`

I'm actually using Ionic so I go for `ionic cordova plugin add https://github.com/ostownsville/cordova-plugin-fcm.git` just to be on the safe side (this is irrelevant).

Here is my ionic info:
```
cli packages: (/Users/chrispalmer/Documents/Software/CollegeOne/1app/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 browser 4.1.0 ios 4.5.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 6.0.0
    Node              : v6.9.4
    npm               : 3.10.10
    OS                : macOS Sierra
    Xcode             : Xcode 9.0 Build version 9A235

Misc:

    backend : pro
```

I'm also running OS 10.12.6.
My node version is lower than yours.
So is my npm version.

Ideally once we get this thing up on NPM you won't encounter these issues. We are trying to squash the last bugs in this thing before we do that.

**Comment by idvl** [comment]
Hi @junerockwell 

Did you try running `sudo cordova plugin add git+https://github.com/ostownsville/cordova-plugin-fcm.git`? 
It did the job for me on a similar issue.

**Comment by CowboyCode** [comment]
Close this...
