### ISSUE TITLE
Specifiy a sound for notification

### ISSUE THREAD

**Issue by luigi37** [ostownsville/cordova-plugin-fcm#22]
Hi, I'm not clear on how to specify a special sound for notification.

- Is the choice of the sound driven by the notification? Which options drives it?
- Which format needs to be the sound?
- Which name, extension and path for the sound file?

I know it's documented but I was not able to use it yet...

Thanks

**Comment by luigi37** [comment]
Ok found this for Android and it works:

https://github.com/fechanique/cordova-plugin-fcm/issues/189

```
{
  ...,
  "sound": "nameFileWithoutExtension",
  ...
}
```

> I use cordova and I have put my MP3 in %cordovaRootFolder%/Platforms/Android/res/raw

Where should be put the file for iOS? Same style?

**Comment by chrisjpalmer** [comment]
Hi there.

I am not 100% aware on how to do this either. 

This is the payload specification for APNS. It assumes you have a web server talking to the APNS endpoint. Obviously firebase does this on behalf of us and we need to specify our sound options from Firebase. The documentation suggests that the sound option will be fetched from the 'app's main bundle'. The question is, how to get it into the main bundle.

Give me some more time, I will do some research.

![image](https://user-images.githubusercontent.com/29791291/31867128-8e0e83aa-b7d5-11e7-9449-850944708544.png)
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1

**Comment by luigi37** [comment]
Thanks a lot. I have the suspect the file needs also to be in CAF format...

**Comment by CowboyCode** [comment]
Addition
https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

Sound key
The sound to play when the device receives the notification.
**Supports "default" or the filename of a sound resource bundled in the app. Sound files must reside in /res/raw/**.

**Comment by Radecom** [comment]
I managed to put icon and custom sound by following this [article](https://medium.com/@ing.ajvillalon/how-to-set-a-custom-icon-for-notifications-on-android-d03a4ad4414e).
I'm working with [Cordova plugin Fcm](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated) in Ionic 4
And so far everything is going well
