### ISSUE TITLE
FirebaseAnalytics.h file not found fatal error

### ISSUE THREAD

**Issue by junerockwell** [ostownsville/cordova-plugin-fcm#23]
Please see screenshot below for the issue:
![screen shot 2017-10-19 at 9 15 42 am__](https://user-images.githubusercontent.com/5051574/31782120-e80b3ab2-b4ae-11e7-9654-047dd6c60d90.png)

Since I couldn't install this specific `cordova-plugin-fcm` via Cordova CLI/NPM (see issue #20), I decided to download straight from GitHub. I copied over the files in to the Cordova project's plugins folder. Then I typed `sudo cordova build ios` and I get this fatal error. Looking through the path in iOS, I do not see a folder `FirebaseAnalytics` or a `FirebaseAnalytics.h` file. 

![screen shot 2017-10-19 at 9 25 08 am__](https://user-images.githubusercontent.com/5051574/31782359-864fa85c-b4af-11e7-9c81-4d56b44021f8.png)

So far, I have not tried Android. 

Using:
MacOSX 10.12.16
Node: v8.0.0
Npm: v5.0.0
Cordova: 7.0.1
Ionic CLI: 3.7.0
Ionic Framework: 1.3.3

**Comment by chrisjpalmer** [comment]
Hi @junerockwell 

I am looking at your issue now. Now you may think that the import path is wrong but actually the path <FirebaseAnalytics/FirebasAnalytics.h> is specifying:

- _FirebaseAnalytics_ **framework**

- _FirebaseAnalytics.h_ file within this framework

The FirebaseAnalytics framework is located in plugins/cordova-plugin-fcm/src/ios/Firebase/Analytics/FirebaseAnalytics.framework

Inside the framework itself are a number of headers:

![image](https://user-images.githubusercontent.com/29791291/31867094-d3e742dc-b7d4-11e7-81fd-393ef6f12200.png)


I am unfortunately not able to replicate the issue on my machine. Try the following and if no luck, post back:

- Can you see the frameworks correctly underneath the Analytics folder?
![image](https://user-images.githubusercontent.com/29791291/31867061-6d118c52-b7d4-11e7-8408-c8ac4506642c.png)

- Which version of cordova ios are you using? I am using 4.5.0

- Which version of git are you using to clone the source? I am using `git version 2.13.5 (Apple Git-94)`

**Comment by CowboyCode** [comment]
@junerockwell 
In case that you use ios@4.5.x, you need to remove the cordova-plugin-console (may named differently, cant 100% remember), that plugin is already integrated. 

May remove the plugin and remove and add the ios platform.
With the newest version, you need to make sure, for Android, that you use android@6.2.x, the 6.3 version has issues. See changes in read me.

Close this for now
