### ISSUE TITLE
Buttons in the notification

### ISSUE THREAD

**Issue by luigi37** [ostownsville/cordova-plugin-fcm#26]
Hi, is it possible to get buttons on the notification?

**Comment by CowboyCode** [comment]
No, only programmatically in your code, when you app is receiving the message. Not in the system/background messages.

**Comment by luigi37** [comment]
Any plan to add it? It seems possible in principle (at list on iOS) https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md

**Comment by CowboyCode** [comment]
Do you mean badge?

**Comment by luigi37** [comment]
Nope: action buttons....

**Comment by luigi37** [comment]
I found this reference:
https://material.io/guidelines/patterns/notifications.html#notifications-behavior

> A notification may offer up to three actions when expanded. It should not duplicate the action taken from tapping on the notification body.
