### ISSUE TITLE
Error in build since yesterday

### ISSUE THREAD

**Issue by luigi37** [ostownsville/cordova-plugin-fcm#28]
Hi all,
started receiving this on 
`cordova run android`

```
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.google.firebase:firebase-core:11.4.2.
     Required by:
         project :
   > Could not find com.google.firebase:firebase-messaging:11.4.2.
     Required by:
         project :
```

It seems linked to this but I'm not totally sure...
https://github.com/NativeScript/push-plugin/issues/144

**Comment by chrisjpalmer** [comment]
Hi Luigi. Are you aware that now you need to install an additional plugin for Google Play Services?

See the readme.

**Comment by luigi37** [comment]
Yes, right. Sorry. I was playing around with another plugin and I did miss this.
