### ISSUE TITLE
iOS Notification Sound in "Do Not Disturb mode"

### ISSUE THREAD

**Issue by luigi37** [ostownsville/cordova-plugin-fcm#32]
Hi,
on Android, you can exclude app from  the "Do not disturb mode" and as long as you select appropriate option, the notification will be issued also with sound.
Is there anything similar in iOS?

Actually, in FCM I'm already using
`'priority'`  => 'high',

**Comment by chrisjpalmer** [comment]
Very sorry but I dont have time to research this but do check out the APNS documentation, If there is native support within APNS its just a matter of using Firebase to control it.

**Comment by luigi37** [comment]
Understood Chris and thanks again for all the great work on this plugin! I found priority option and in effect it gets the notification delivered. Only with no sound... I'm wondering, not being an iPhone user, if any app can send sound notification to iPhone in do not disturb more at all...

**Comment by chrisjpalmer** [comment]
I think not, knowing apple! It's the kind of thing that Apple would not support haha!

**Comment by chrisjpalmer** [comment]
No problem at all Luigi. Thanks for the encouragement!

**Comment by luigi37** [comment]
Ok. I will ask my Apple friends and check again apn doc :-)

**Comment by luigi37** [comment]
After having checked around it seems there is no option on site to skip do not disturb. Anyway, Apple friends confirmed they usually silence app they don't need and keep loud the ones they want. So I think we can close
