### ISSUE TITLE
Case Sensitive Issue (dropbox)

### ISSUE THREAD

**Issue by luigi37** [ostownsville/cordova-plugin-fcm#8]
Hi all,
I'm working on Linux and Mac which are case sensitive. Unfortunately, to sync both I need dropbox and it looks like (to allow windows sync in general) it threats the files as case insensitive.
In other words, every time I have files with same letters but different capitalisation, dropbox changes them to "name_of_the_file conflict with capilasation something"...
Would be possible to change in ios/src the directory names 
Firebase
firebase
?
Thanks
Luigi

**Comment by chrisjpalmer** [comment]
Hi Luigi. This problem could be solved using git. 

1. Download and install git on both your mac and linux
2. Create an account on github OR bitbucket => bitbucket allows free private repositories.
3. On either bb or gh, create a new repository
4. Go to your project dir in your Mac and perform git init. Perform an initial commit
5. Follow the instructions online from bb or gh about how to link your newly created repo to your local git repo.
6. Pull the project on your linux machine using git pull

I recommend not using dropbox as it can sometimes corrupt your project if it has syncing conflicts.

Hope that helps!

**Comment by luigi37** [comment]
Thanks Chris. But.... is it really needed to have the two folders with same name and different capitalisation? Which option would you reccomend to replace Dropbox? My Mac account is on macincloud service. Thanks

**Comment by chrisjpalmer** [comment]
Hi Luigi

I think what you are referring to is the Firebase and firebase folders in the iOS side of the plugin. I think you are right. This is going to cause issues and I'm surprised it hasn't already. Later today Im going to fix that issue and put up another P.R.

Thanks Luigi

**Comment by chrisjpalmer** [comment]
Still recommend using git!

**Comment by luigi37** [comment]
Thanks :-)

**Comment by luigi37** [comment]
Any chance yet to change dirs name?

**Comment by chrisjpalmer** [comment]
Hi Luigi

https://github.com/ostownsville/cordova-plugin-fcm/pull/12 <https://github.com/ostownsville/cordova-plugin-fcm/pull/12>

Here are the goods.

Chris

**Comment by luigi37** [comment]
Thank you!
